language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
env:
  - IS_CI: true

# S: Build Lifecycle
install:
  - ./scripts/install.sh
before_script:
  - echo "start"
script:
  - npm run lint
  - npm run test:unit
  - npm run build
after_script:
  - echo "done"
# E: Build LifeCycle

after_success:
  - test $TRAVIS_PULL_REQUEST = "false" &&
    npx travis-deploy-once "npx semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
